"""add webhook events table

Revision ID: h3d6i9406907
Revises: g2c5h8295796
Create Date: 2026-01-27 16:02:40.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'h3d6i9406907'
down_revision: Union[str, None] = 'g2c5h8295796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_index('ix_webhook_events_idempotency_key', 'webhook_events', ['idempotency_key'], unique=True)
    op.create_index('ix_webhook_events_next_retry_at', 'webhook_events', ['next_retry_at'], unique=False)
    op.create_index('ix_webhook_events_source', 'webhook_events', ['source'], unique=False)
    op.create_index('ix_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.create_index('ix_webhook_events_status_retry', 'webhook_events', ['status', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_events_status_retry', table_name='webhook_events')
    op.drop_index('ix_webhook_events_status', table_name='webhook_events')
    op.drop_index('ix_webhook_events_source', table_name='webhook_events')
    op.drop_index('ix_webhook_events_next_retry_at', table_name='webhook_events')
    op.drop_index('ix_webhook_events_idempotency_key', table_name='webhook_events')
    op.drop_index('ix_webhook_events_event_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
